version: '3.4'

services:
  clinicsearchapi:
    image: clinicsearchapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
